config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end

  resources :weight_data

  get 'paid', to: 'home#paid'

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :weight_data
end

app/models/weight_datum.rb
class WeightDatum < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  layout "application"
  def index
    Time.zone = "Central Time (US & Canada)"
    @users = User.all

    @weight_data = {}

    @users.order(:id).each do |user|
      user_data = @weight_data[user.id] = {}

      user.weight_data.group_by{|d| (d.created_at.in_time_zone).all_week}.each do |date, weights|
        user_data[date.first.strftime("%b %d, %Y")] = weights.max_by(&:created_at).weight
      end

      @this_week = {}
      @users.order(:id).each do |user|
        data = @this_week[user.id] = {}
        prev_weight = ""

        if true #new way
          date = Date.today()-6.days
          loop do
            weight = user.weight_data.select{|d| (d.created_at.in_time_zone).to_date == date}.first
            if weight.nil?
              if prev_weight == ""
                data[date] = user.weight_data.first.weight
              else
                data[date] = prev_weight.to_i unless date == Date.today()
              end
            else
              data[date] = weight.weight
              prev_weight = weight.weight
            end
            date = date + 1.day
            break if date == Date.today()+1.day
          end
        else #old way
          Date.today().all_week.each do |date|
            if date <= Date.today()
              weight = user.weight_data.select{|d| (d.created_at.in_time_zone).to_date == date}.first
              if weight.nil?
                data[date] = prev_weight unless date == Date.today()
              else
                data[date] = weight.weight
                prev_weight = weight.weight
              end
            end
          end
        end #end new/old if
      end
    end
  end

  def paid
    user = User.find(params[:id])
    user.update_attribute('paid', true)
    render :nothing => true
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/weight_data_controller.rb
class WeightDataController < ActionController::Base
  layout "application"
  def new
    @weight = WeightDatum.new
  end

  def create
    WeightDatum.create(weight_datum_params)
    redirect_to "/"
  end

  def update
    data = WeightDatum.find(params[:id])
    data.update_attributes(weight_datum_params)
    flash[:notice] = "Today's weight was updated to #{data.weight}"
    redirect_to "/"
  end

  private

  def weight_datum_params
    params.require(:weight_datum).permit(:weight, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%Time.zone = "Central Time (US & Canada)"%>
<nav class="navbar navbar-light bg-light">
  <div>
    <a class="navbar-brand" href="#">HotBods</a>
    <%#= link_to('Enter Weight', new_user_session_path)  %>
  </div>

  <div>
    <% if user_signed_in? %>
      <%#= link_to "Edit User", edit_user_registration_path %>
      <%="Hello #{current_user.first_name}" if user_signed_in?%> |
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign Up', new_user_registration_path %> |
      <%= link_to 'Login', new_user_session_path %>
    <% end %>
  </div>
</nav>


<div class="container" style="margin-top: 30px">
  <div class="row">
    <div class="col-lg-4">
      <div class="card">
        <div class="card-header">
          Current Weights
        </div>
        <div class="card-block">
          <p class="card-text">
            <%@users.order(:id).each do |user|%>
              <%=user.first_name%> - <%=(weight = user.weight_data.order(:created_at).last.try(:weight)).nil? ? "n/a" : weight%> | <%=(((user.weight_data.first.weight - user.weight_data.last.weight) / user.weight_data.first.weight) * 100).round(2)%>% Change<br/>
            <%end%>
          </p>
        </div>
      </div>

      <% if user_signed_in? %>
        <%unless current_user.paid%>
          <div class="card" style="margin-top: 30px">
            <div class="card-header">
              Buy In
            </div>
            <div class="card-block">
              <p class="card-text">
                You owe your buy in money of $50. Click <%=link_to "here", "https://www.paypal.me/BryanCurry", id: "pay_due"%> to pay.
              </p>
            </div>
          </div>
        <%end%>
      <%end%>


      <div class="card" style="margin-top: 30px">
        <div class="card-header">
          Log Your Weight<br />
        </div>
        <div class="card-block">
          <% if user_signed_in?%>
            <%today = Date.today%>
            <%if current_user.weight_data.map{|t| (t.created_at.in_time_zone).to_date}.include?(today)%>
              <p id="text-to-hide" class="card-text">
                You already have entered a weight for this week. Come back tomorrow!<br>
                <a href="#" onclick="return false;" id="edit_weight">Edit Today's Weight</a>
              </p>
              <%=form_for(current_user.weight_data.select{|t| (t.created_at.in_time_zone).to_date == today}.first, html: {style: "display: none"}) do |f|%>
                <div class="form-group">
                  <%= f.label :weight %><br />
                  <%= f.text_field :weight, class: "form-control" %>
                </div>

                <div class="actions">
                  <%= f.submit "Update Weight", class: "btn btn-primary"%>
                  <%=link_to "Cancel", "", onclick: "return false;", class: "text-danger ml-3"%>
                </div>
              <%end%>
            <%else%>
              <%= form_for WeightDatum.new, url: {action: "create", controller: "weight_data"}, remote: true, class: "form-inline" do |f| %>
                <div class="form-group">
                  <%= f.label :weight %>
                  <%= f.text_field :weight, placeholder: "To the nearest 10th", class: "form-control" %>
                </div>

                <%=f.hidden_field :user_id, value: current_user.id%>

                <div class="actions">
                  <%= f.submit "Log Weight", class: "btn btn-primary"%>
                </div>
              <% end %>
            <%end%>
          <%else%>
            <%= link_to 'Sign Up', new_user_registration_path %> or <%= link_to 'Login', new_user_session_path %> to record your weight for this week
          <%end%>
        </div>
      </div>

      <div class="card" style="margin-top: 30px">
        <div class="card-header">
          Motivation for the Week
        </div>
        <div class="card-block">
          <p class="card-text">
            <img src="http://mrwgifs.com/wp-content/uploads/2014/03/Grumpy-Man-Doesnt-Care-About-You-Weight-Loss-Journey-In-Gif-Comic-By-Explosm.gif" width="100%">
          </p>
        </div>
      </div>

    </div>
    <div class="col-lg-8">
      <div style="height: 30px" class="d-xs-block d-md-none"></div>
      <div class="card">
        <div class="card-block">
          <a href="" id="show_week" class="active" onclick="return false;">This Week</a> | <a href="" id="show_all" onclick="return false;">All Time</a>
          <%all_weights = @this_week.values.map{|v| v.values}.flatten%>
          <div id="this_week"><%= line_chart @users.map { |user| {name: user.first_name, data: @this_week[user.id]}}, min: all_weights.min.round - 15, max: all_weights.max.round + 15 %></div>
          <br/>
          <%all_weights = @weight_data.values.map{|v| v.values}.flatten%>
          <div id="all_time" class="invisible"><%= line_chart @users.map { |user| {name: user.first_name, data: @weight_data[user.id]}}, min: all_weights.min.round - 15, max: all_weights.max.round + 15 %></div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  <%if user_signed_in?%>
    $("#pay_due").on('click', function() {
      $.ajax({
        url: "<%=paid_url%>",
        data: {'id': <%=current_user.id %>}
      })
    });
  <%end%>

  $("#show_week").on('click', function() {
    $("#this_week").show()
    $("#all_time").hide()
    $(this).addClass('active')
    $("#show_all").removeClass('active')
  });

  $("#show_all").on('click', function() {
    $("#this_week").hide()
    $("#all_time").show()
    $("#all_time").removeClass('invisible')
    $(this).addClass('active')
    $("#show_week").removeClass('active')
  });

  $("#edit_weight").on('click', function() {
    $(".edit_weight_datum").show()
    $("#text-to-hide").hide()
  });

  $(".text-danger").on('click', function() {
    $(".edit_weight_datum").hide()
    $("#text-to-hide").show()
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hotbods</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap-growl.min'%>
  <%= csrf_meta_tags %>
  <style>
    .card-block {
      -webkit-box-flex: 1;
      -webkit-flex: 1 1 auto;
      -ms-flex: 1 1 auto;
      flex: 1 1 auto;
      padding: 1.25rem;
    }

    a.active {
      color: #212529;
      cursor: default;
      text-decoration: none;
    }
  </style>
</head>
<body style="background: url('assets/background.png'); background-size: cover">

<%if !!notice%>
  <script>
    $.bootstrapGrowl("<%= notice %>", {
      type: 'success',
      delay: 3000,
      width: 'auto',
    });
  </script>
<%end%>
<%if !!alert%>
  <p class="alert"><%= alert %></p>
<%end%>
<%= yield %>

</body>
</html>